name: 'Install Dependencies'
description: 'Shared composite action to install pnpm and workspace dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install Workspace Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
