# Automatically generated by sync-contracts.ts. Do not edit manually.
# pylint: disable=invalid-name,missing-class-docstring,missing-module-docstring,line-too-long,unused-import
from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import Field
from dev_tools.models.base import CamelCaseModel

CodeReviewParseError = Literal['missing_closing_tag', 'truncated_json', 'incomplete_findings', 'invalid_json']

class IssueSummary(CamelCaseModel):
    number: int
    title: str
    html_url: str
    state: str

class ReviewFinding(CamelCaseModel):
    id: str
    file: str
    issue: str
    status: Literal['open', 'resolved']
    confidence: Literal['high', 'medium', 'low']
    severity: Optional[Literal['HIGH', 'MEDIUM', 'LOW']] = None
    line: Optional[int] = None
    snippet: Optional[str] = None
    fix_summary: Optional[str] = None
    counterexample: Optional[str] = None

class CodeReviewState(CamelCaseModel):
    findings: List[ReviewFinding] = Field(default_factory=list)

class CodeReviewResult(CodeReviewState):
    feedback: str
    role: str
    tokens: int
    cost: float
    model_name: str
    llm_verdict: Literal['pass', 'warn', 'fail']
    is_truncated: Optional[bool] = None
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    cache_tokens: Optional[int] = None
    parse_error: Optional[CodeReviewParseError] = None

class VisualReviewFinding(CamelCaseModel):
    id: str
    route: str
    issue: str
    status: Literal['open', 'resolved']
    fix_summary: Optional[str] = None

class RouteReview(CamelCaseModel):
    route: str
    severity: Literal['LOW', 'MEDIUM', 'HIGH']
    difference_percent: float
    feedback: str
    tokens: int
    cost: float
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    cache_tokens: Optional[int] = None
    model_name: Optional[str] = None
    llm_verdict: Optional[Literal['pass', 'fail', 'warn']] = None
    findings: Optional[List[VisualReviewFinding]] = None
    is_truncated: Optional[bool] = None
    role: Optional[str] = None

class AIRunLogEntry(CamelCaseModel):
    timestamp: str
    type: Literal['code-review', 'visual-review']
    input_tokens: int
    output_tokens: int
    duration_ms: int
    cost: float
    model: Optional[str] = None
    cache_tokens: Optional[int] = None
    total_tokens: Optional[int] = None
    verdict: Optional[str] = None
    pr: Optional[str] = None
    route: Optional[str] = None
    error: Optional[str] = None
    is_truncated: Optional[bool] = None
    parse_error: Optional[str] = None
    raw_response: Optional[str] = None
    findings: Optional[List[Any]] = None
    input_chars: Optional[int] = None
